### ISSUE TITLE
Is it possible to make a Discoverer based on http://oembed.com/providers.json?

### ISSUE THREAD

**Issue by djowett** [pyembed/pyembed#46]
That's the closest piece of authoritative data to official oembed providers, right?

http://oembed.com/providers.json

**Comment by matt-thomson** [comment]
Yes, that looks like the right thing to do (that JSON list is new since I last looked at http://oembed.com).  I'll take a look at this in the near future.

**Comment by matt-thomson** [comment]
Unfortunately the data in http://oembed.com/providers.json is incomplete - some of the providers don't have a scheme (i.e. a URL pattern that the provider can embed).  I'll see about putting in a PR on the oEmbed project to get those added.

**Comment by matt-thomson** [comment]
Actually, I think this is OK - the providers without schemes are the ones where the URL pattern to match covers many domains (e.g. Embedly, Wordpress).  It'd be better just to ignore those ones.

**Comment by djowett** [comment]
thanks @matt-thomson  glad you also feel it's "the right thing to do".

**Comment by matt-thomson** [comment]
The newly released v1.2.0 should do this - let me know if you see any issues.

I noticed on the linked issue that you were using a custom renderer.  As an alternative, you might like to use `pyembed-markdown` or `pyembed-rst`, which provider renderers that allow you to write your embeddings as Markdown/reStructuredText templates.  More details [here](http://pyembed.github.io/customization/).
