### ISSUE TITLE
Not maintained?

### ISSUE THREAD

**Issue by micahjsmith** [pyembed/pyembed#67]
Is this project/organization currently maintained? #64 makes this more or less useless and has been open for a long time. Are there any alternatives or forks that are recommended? Thanks.

**Comment by matt-thomson** [comment]
Hi @micahjsmith, thanks for getting in touch, and apologies for the delay in replying!

You're right in that this project is now unmaintained: real life has taken over and I sadly don't have the time to work on it.

I'm not aware of any particular alternatives or forks (but I haven't been working in this space for a while).

**Comment by micahjsmith** [comment]
Of course, these things happen -- would you consider [archiving](https://github.blog/2017-11-08-archiving-repositories/) the repository or adding a banner to the README to indicate this?

**Comment by matt-thomson** [comment]
Yep, have done that: https://github.com/pyembed/pyembed/commit/c9b7dfd42e15e6a8cec536378397211940b9ba20.
